### ISSUE TITLE
Invalid date issue in Availability after submit for edit Meeting Window with Widget

### ISSUE THREAD

**Issue by balvinder294** [Kloudless/meeting-scheduler#3]
Hi, 
There is one issue in Edit Meeting Window.
First of all.
i am using as a widget with JS script in pop up mode only. 
Create window(Setup view) is working fine and creating meeting Window.

But while ediiing meeting window with Edit View and saving there is issue.

As you can see, the meeting window is getting data correctly, in below response. I have set up two time slots.
```
{
  "id": "AWlZStS6iNEjtq8XueXN",
  "booking_calendar_id": "fYmFsdmluZGVyMjk0QGdtYWlsLmNvbQ==",
  "duration": 15,
  "availability": {
    "end_repeat": "NEVER",
    "available_times": [
      {
        "start": "04:00:00",
        "end": "17:00:00",
        "recurring": {
          "weekday": "SUN",
          "month": "*",
          "day": "*"
        }
      },
      {
        "start": "08:00:00",
        "end": "17:00:00",
        "recurring": {
          "weekday": "MON",
          "month": "*",
          "day": "*"
        }
      }
    ]
  },
  "time_buffer_before": 0,
  "time_buffer_after": 0,
  "time_slot_interval": 30,
  "availability_range": 30,
  "public_choice_token": "P9470r88uVjBSlHHCkDEu0fCnjNK9T",
  "time_zone": "Asia/Kolkata",
  "api": "meeting_scheduler",
  "allow_event_metadata": false,
  "default_event_metadata": {},
  "recaptcha_site_key": "6Lcm7KwUAAAAAIzQJMcYKB7MgfqL5bN62-mEOJh-"
}
```

but while clicking update(Saving) after making edits, there is one error thrown as 400 with below response 
```
message: availability: 
{
    'available_times': [
          {
             'start': [u'The format is invalid. Must be in "hh:mm:ss". (u\'Unknown string format:\', u\'Invalid date\')'], 
             'end': [u'The format is invalid. Must be in "hh:mm:ss". (u\'Unknown string format:\', u\'Invalid date\')']
          }, 
          {
             'start': [u'The format is invalid. Must be in "hh:mm:ss". (u\'Unknown string format:\', u\'Invalid date\')'],
             'end': [u'The format is invalid. Must be in "hh:mm:ss". (u\'Unknown string format:\', u\'Invalid date\')']}]
}.
```
But this should not be the case as The availability object is not available to edit and it should be sent same as above response from Api.
But the param i am getting while making update api call below you see, are going as invalid.
```
{  
   "id": "AWlZStS6iNEjtq8XueXN",
   "booking_calendar_id": "fYmFsdmluZGVyMjk0QGdtYWlsLmNvbQ==",
   "duration": 15,
   "time_zone":"Asia/Kolkata",
   "availability_range":30,
   "time_buffer_before":0,
   "time_buffer_after":0,
   "time_slot_interval":30,
   "allow_event_metadata":false,
    "availability":{
       "end_repeat":"NEVER",
       "available_times":[
              {
                 "start":"Invalid date",
                 "end":"Invalid date",
                 "recurring":{
                      "month":"*",
                      "day":"*",
                      "weekday":"SUN"
                  }
              },
              {
                  "start":"Invalid date",
                  "end":"Invalid date",
                  "recurring":{
                       "month":"*",
                       "day":"*",
                       "weekday":"MON"
                   }
              }
       ]
   }
}
```

Please help me in this case. Also this meeting scheduler, i am currently integrating in our application. So this only issue i faced.

**Comment by fsworld009** [comment]
Hi, thanks for reporting.

From your comments, I think there might be an issue when loading Meeting Window in edit mode in the code. You are supposed to be able to edit availability, we are currently looking into it.

**Comment by balvinder294** [comment]
Hi, Thanks for replying.
Here are screens for reference.
Error in console when i initialy open edit window
![error 1](https://user-images.githubusercontent.com/25227213/68400052-65f0e200-019d-11ea-9027-8dacf9109176.png)

Screen showing availablity edit options, only advanced edit options available. Time slots are not editable, which i think is causing the issue.
Maybe this helps.
![error 2](https://user-images.githubusercontent.com/25227213/68400053-65f0e200-019d-11ea-9746-a427023214dd.png)

Thanks.

**Comment by vinodc** [comment]
Hi @balvinder294 . I'm confirming we have escalated this issue internally and are hoping to work towards a resolution tomorrow. We'll be in touch with further details.

**Comment by fsworld009** [comment]
Hi @balvinder294, we just released `v1.6.2` to fix this issue.

I'll close this issue for now, but feel free to response if you still face this issue, thanks.

**Comment by balvinder294** [comment]
Thanks, @vinodc @fsworld009 for the quick fix. I will check and report if any issue.

**Comment by balvinder294** [comment]
Thanks, it is working now. And also meeting time slots can be updated now.

**Comment by balvinder294** [comment]
Hi there, I hope everything is good. This time not an issue, but like a query to check. If there is something available/in progress to integrate natively on android/ios. If there is something available, it will be good if you can point me to the same.
if there is nothing yet, please let me know the APIs I need to call, so we can integrate the APIs with our own UI in the app.
Thanks.

**Comment by vinodc** [comment]
Hi @balvinder294. Thanks for reaching out. We currently do not yet have public documentation on how to select time slots programmatically, so only support embedding the time slot selection screen via a browser UI component that uses the JavaScript-based version. If this is acceptable to use, you could use that at the current time until we make our documentation for that API publicly available. 

The currently documented [API endpoints](https://github.com/kloudless/meeting-scheduler#endpoints) are only for creating and managing a Meeting Window and not for selecting a time slot. This is a work in progress and we will reach out to you once it's complete.

**Comment by balvinder294** [comment]
Thanks, @vinodc I will try to make it work with like existing Apis and flow.
